=== xuanximoming/key/Public/自动任务处理/JobTasks/BasisData/XMLFile/BasisDataSynchSetting.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Wang Yi (Winning) -->
<xs:schema xmlns:kw="http://www.DrectSoft.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.DrectSoft.com/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="BasisDataSynchSetting">
		<xs:annotation>
			<xs:documentation>基础数据同步</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TableMapping" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>数据映射设置</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PreHandleSentence" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>需要在目标数据库预执行的语句</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="DataSource" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>数据来源设置</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="SelectSentence" type="xs:string" minOccurs="0">
											<xs:annotation>
												<xs:documentation>从源库筛选数据的SQL语句(为空时使用公共设置)</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="SourceTable" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>源库中的表名</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="FilteCondition" type="xs:string">
										<xs:annotation>
											<xs:documentation>对源表数据进行过滤的条件</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="SelectSentence" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>公共的从源库筛选数据的SQL语句</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="OtherSentence" type="xs:string" minOccurs="0">
								<xs:annotation>
									<xs:documentation>公共的需要在目标库另外执行的处理语句</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="TargetTable" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>目标库中的表名</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="Enabled" type="xs:boolean" use="required">
							<xs:annotation>
								<xs:documentation>是否启用</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="NameField" type="xs:string">
							<xs:annotation>
								<xs:documentation>名称字段的列名，用于更新对应的拼音五笔字头</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xuanximoming/key/Public/自动任务处理/JobTasks/BasisData/XMLFile/BasisDataSynchSetting1.xml
<?xml version="1.0" encoding="utf-8"?>
<BasisDataSynchSetting xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.yidansoft.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.yidansoft.com/
BasisDataSynchSetting.xsd">
	<TableMapping TargetTable="Ward" Enabled="true" NameField="name">
		<DataSource SourceTable="YD_WARDS"/>
		<SelectSentence>SELECT *FROM YD_WARDS where VALID=1</SelectSentence>
	</TableMapping>
	<TableMapping TargetTable="DEPARTMENT" Enabled="true" NameField="name">
		<DataSource SourceTable="YD_DEPARTMENTS"/>
		<SelectSentence>SELECT *FROM YD_DEPARTMENTS</SelectSentence>
	</TableMapping>
	<TableMapping TargetTable="DEPT2WARD" Enabled="true">
		<DataSource SourceTable="YD_DEPT2WARD"/>
		<SelectSentence>select *from YD_DEPT2WARD</SelectSentence>
	</TableMapping>
	<TableMapping TargetTable="Users" Enabled="true" NameField="Name">
		<DataSource SourceTable="yd_users"/>
		<SelectSentence> select  * from yd_users where VALID=1</SelectSentence>
		<OtherSentence>update Users set GroupID = '00,' where ID = '00' and (GroupID is null or GroupID = '')</OtherSentence>
	</TableMapping>
  <TableMapping TargetTable="User2dept" Enabled="true" >
    <DataSource SourceTable="yd_user2dept"/>
    <SelectSentence> select  * from yd_user2dept </SelectSentence>
  </TableMapping>
  <TableMapping TargetTable="DIAGNOSIS" Enabled="true" >
    <DataSource SourceTable="YD_DIAGNOSIS"/>
    <SelectSentence> select  * from YD_DIAGNOSIS </SelectSentence>
  </TableMapping>
</BasisDataSynchSetting>
